apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: demo-api
  namespace: default
spec:
  image: ghcr.io/sabinghost19/demo-vulnerable-fastapi:v1.0.2
  replicas: 2
  securityPolicyRef:
    name: demo-app-security-policy
  networkZeroTrust:
    ingressAllowedFrom:
      - namespace: api-gateway
    egressAllowedTo:
      - namespace: database
        ports: [5432]
  wafConfig:
    mode: Block
    appProfile: REST-API
  runtimeSecurity:
    allowedPaths:
      - /tmp/app-data
    onCompromise: Isolate
