apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zta-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zta-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zta-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zta-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "zta-operator.serviceAccountName" . }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["kopf", "run", "{{ if .Values.operator.watchAllNamespaces }}--all-namespaces{{ else }}--namespace={{ .Release.Namespace }}{{ end }}", "-m", "zta_operator.operator"]
          env:
            - name: LOG_LEVEL
              value: {{ .Values.operator.logLevel | quote }}
            - name: TALON_NAMESPACE
              value: {{ .Values.operator.talonNamespace | quote }}
            - name: TALON_CONFIGMAP_NAME
              value: {{ .Values.operator.talonConfigMapName | quote }}
            - name: TALON_CONFIGMAP_KEY
              value: {{ .Values.operator.talonConfigMapKey | quote }}
            - name: INGRESS_CLASS_NAME
              value: {{ .Values.operator.ingress.className | quote }}
            - name: INGRESS_PATH
              value: {{ .Values.operator.ingress.path | quote }}
            - name: INGRESS_PATH_TYPE
              value: {{ .Values.operator.ingress.pathType | quote }}
            - name: OAUTH2_AUTH_URL
              value: {{ .Values.operator.ingress.authUrl | quote }}
            - name: OAUTH2_AUTH_SIGNIN
              value: {{ .Values.operator.ingress.authSigninTemplate | quote }}
            - name: OAUTH2_AUTH_RESPONSE_HEADERS
              value: {{ .Values.operator.ingress.authResponseHeaders | quote }}
            - name: OAUTH2_GROUPS_HEADER
              value: {{ .Values.operator.ingress.groupsHeader | quote }}
            - name: OAUTH2_GROUPS_HEADER_FALLBACK
              value: {{ .Values.operator.ingress.groupsHeaderFallback | quote }}
            - name: OAUTH2_PROXY_SERVICE_NAME
              value: {{ .Values.operator.ingress.oauth2ServiceName | quote }}
            - name: OAUTH2_PROXY_NAMESPACE
              value: {{ .Values.operator.ingress.oauth2ServiceNamespace | quote }}
            - name: OAUTH2_PROXY_PORT
              value: {{ .Values.operator.ingress.oauth2ServicePort | quote }}
            - name: OAUTH2_INGRESS_PATH
              value: {{ .Values.operator.ingress.oauth2IngressPath | quote }}
            - name: GUAC_GRAPHQL_URL
              value: {{ .Values.operator.guac.graphqlUrl | quote }}
            - name: GUAC_COLLECTOR_URL
              value: {{ .Values.operator.guac.collectorUrl | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
