apiVersion: apps/v1
kind: Deployment
metadata:
  name: zta-operator
  namespace: devsecops-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zta-operator
  template:
    metadata:
      labels:
        app: zta-operator
    spec:
      serviceAccountName: zta-operator
      volumes:
        - name: admission-tls
          secret:
            secretName: zta-admission-tls
            optional: true
      containers:
        - name: webhook
          image: ghcr.io/sabinghost19/zta-operator:v0.1.0
          imagePullPolicy: IfNotPresent
          command: [ "python", "-m", "zta_operator.webhook" ]
          ports:
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: admission-tls
              mountPath: /tls
              readOnly: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests: { cpu: "10m", memory: "64Mi" }
            limits:   { cpu: "200m", memory: "256Mi" }
        - name: operator
          image: ghcr.io/sabinghost19/zta-operator:v0.1.0
          imagePullPolicy: IfNotPresent
          command: [ "kopf", "run", "--all-namespaces", "-m", "zta_operator.operator" ]
          env:
            - name: GUAC_GRAPHQL_URL
              value: "http://graphql-server.guac.svc.cluster.local:8080/query"
            - name: GUAC_COLLECTSUB_URL
              value: "collectsub.guac.svc.cluster.local:2782"
            - name: LOG_LEVEL
              value: INFO
            - name: TALON_NAMESPACE
              value: falco-talon
            - name: TALON_CONFIGMAP_NAME
              value: falco-talon-rules
            - name: TALON_CONFIGMAP_KEY
              value: rules.yaml
            - name: INGRESS_CLASS_NAME
              value: nginx
            - name: INGRESS_PATH
              value: /
            - name: INGRESS_PATH_TYPE
              value: Prefix
            - name: OAUTH2_AUTH_URL
              value: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth
            - name: OAUTH2_AUTH_SIGNIN
              value: https://{host}/oauth2/start?rd=$escaped_request_uri
            - name: OAUTH2_AUTH_RESPONSE_HEADERS
              value: X-Auth-Request-User, X-Auth-Request-Email, X-Auth-Request-Groups
            - name: OAUTH2_GROUPS_HEADER
              value: X-Forwarded-Groups
            - name: OAUTH2_GROUPS_HEADER_FALLBACK
              value: X-Auth-Request-Groups
            - name: OAUTH2_PROXY_SERVICE_NAME
              value: oauth2-proxy
            - name: OAUTH2_PROXY_NAMESPACE
              value: oauth2-proxy
            - name: OAUTH2_PROXY_PORT
              value: "80"
            - name: OAUTH2_INGRESS_PATH
              value: /oauth2
